name: Compile and Save as Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile
      run: gcc -Wall -pedantic-errors -o scheduler.out scheduler.c

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: scheduler-executable
        path: ./scheduler.out
